### ISSUE TITLE
Cannot add Category with IE 9

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#10]
Steps:
Open IE 9
Login as group admin or dataentry
CMS Staging URL: http://toa.webdevstaging.com/admin
Create a new Category name and click Add Topic button
Result: Category not created
NOTE: I cannot duplicate this with Chrome ver 32.01700.107 m
The IE full version is 9.0.8112.16421
I reset IE back to factory settings but that did not prevent the issue
I can add Subcategory so the issue may be isolated.

**Comment by ecommarato** [comment]
resolved!

**Comment by rescobar2** [comment]
I can create the Category but in the Cat list the name is blank. I cannot duplicate this in Chrome

**Comment by ecommarato** [comment]
Should be resolved now in IE9

**Comment by rescobar2** [comment]
Verified as fixed 2-26-14 closing
