### ISSUE TITLE
Search for Internal / External flagged FAQS

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#12]
From the group admin and dataentry login.
Will need a way to search for either internal or external FAQs as a tool for FAQ management.

**Comment by ecommarato** [comment]
Would something like the attached mockup work?
![internal-external-search](https://f.cloud.github.com/assets/6640152/2185918/c7a9d360-97dd-11e3-9394-8e43e4a34191.jpg)

**Comment by rescobar2** [comment]
Note to self from Erin
Hi Rick,

The extra cost for the admin search will be $375.  Let me know if we have the green light to proceed!

Thanks,
Erin

**Comment by rescobar2** [comment]
Bob T has approved this change, please proceed

**Comment by rescobar2** [comment]
Verified as fixed 3-12-14 closing
