### ISSUE TITLE
Search Results - Design Cleanup

### ISSUE THREAD

**Issue by ecommarato** [westoforange/TOA-Project-Registry#15]
Suggested cleanup of the search results page is attached.   Would you like to see any more fields added to the display?
![search-results](https://f.cloud.github.com/assets/6640152/2187191/67ba2f44-97f2-11e3-802f-19f3a9417ee7.jpg)

**Comment by rescobar2** [comment]
Great do this

**Comment by rescobar2** [comment]
Verified as fixed 2-19-14 closing
