### ISSUE TITLE
The Deactivated Account message needs to be changed

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#16]
Steps:
Deactivate a user account and then attempt to login.
Result: Message does not have TOA contact information. I don't expect this to happen often. Change contact to Rick Escobar ricke@rickescobar.com 800-733-4748 ext 233

![deactivated-account](https://f.cloud.github.com/assets/6641267/2202012/3d250f44-98f9-11e3-9159-64500006cd66.jpg)

**Comment by rescobar2** [comment]
Update: Lets use FAQadmin@toaelectronics.com as the contact email. We will not need an phone number.

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Can you remove my name so it is more generic

We're sorry, your account appears to have been deactivated. If you believe this to be in error, please contact the TOA site administrator
FAQadmin@toaelectronics.com

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
verified as fixed, closing 4-18-14
