### ISSUE TITLE
Cannot Navigate back from FAQ 

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#17]
Steps:

Login as a User 
Search and open an FAQ
Use browser back arrow
Result: Web page will error. Tested in IE9 and Chrome
NOTE: If I do not actually open the FAQ then I can use back arrow to return to original search page.

**Comment by ecommarato** [comment]
We don't keep the user's search query saved on each page, but we can provide a link back to the FAQ homepage at the bottom of the FAQ detail page.

**Comment by rescobar2** [comment]
Your solution is fine, just improves user experience.

**Comment by ecommarato** [comment]
Resolved with link back to FAQ home

**Comment by rescobar2** [comment]
Verified as fixed 3-12-14 closing

**Comment by rescobar2** [comment]
This bug is back on the Windows Server as of 5-5-14

**Comment by ecommarato** [comment]
There is a link back to 'FAQ Home' on the ticket detail pages.  Do we need to add on the rest of the pages of the site?

**Comment by rescobar2** [comment]
Defer it. Closing as 5-12-14
