### ISSUE TITLE
New password email issued by none TOA email

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#18]
Steps:

Request a new password
Result: Email is from cyms5@west​oforange.co​m
NOTE: I will make a new bug stating TOA needs a general email for sending Admin emails.

**Comment by rescobar2** [comment]
Added as bug

**Comment by rescobar2** [comment]
Didn't mean to close. DOH!

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
verified as fixed, closing
