### ISSUE TITLE
Create new email address for general Admin messages

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#19]
I am going to request from DeviceNet (our IT support) and new address we can use on all
general admin emails. I will update this bug once I have the address and where it should be used.

**Comment by rescobar2** [comment]
I have FAQadmin@toaelectronics.com
Any responses from that email go to me. 
Can we please use this for all the sites admin generic email locations.
Examples: Account Deactivated, password renewal

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Verified as fixed 2-26-14 closing
