### ISSUE TITLE
Redraw Sub Category issue when searching from FAQ result page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#2]
Login as a user
Search for Category: Amplifiers / Sub Category Any
Open result to FAQ page.
Select a Category, then select a Sub Category
Result: Sub Category list redraws the web page as in this example.
See attached jpg

![redraw](https://f.cloud.github.com/assets/6641267/2132275/1232212a-92ad-11e3-83eb-3e6246d3906c.jpg)

NOTE: Can be duplicated in IE 9.0.8112.1642 or Chome 32.0.1700.107m

**Comment by ecommarato** [comment]
Resolved
