### ISSUE TITLE
Delete User Accounts

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#21]
Would it be possible to allow to delete a user account? Currently we can make an account inactive but just from the testing I can see that would be a need to delete an account just to keep the list organized.

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
I could not find how delete account feature works. Is this widget somewhere I'm missing?
Tested 3-12-14

**Comment by rescobar2** [comment]
Trash icon does not appear in IE, works in Chrome

**Comment by ecommarato** [comment]
Should be working in IE now

**Comment by rescobar2** [comment]
Verified as fixed 3-31-14 closing
