### ISSUE TITLE
remove place holder text from Password Recovery page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#22]
From User login page click Forgot Password.
Result: Place holder test: This textarea has not yet been populated with data.
"Please remove this text"

![image](https://f.cloud.github.com/assets/6641267/2340365/0cf45850-a4c2-11e3-922e-20cfa0a0b189.png)

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Verified as fixed 3-12-14 closing
