### ISSUE TITLE
Category will see Subcategory as a Duplicate

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#28]
Pick a random existing Category.
Create Sub-Category call ABC
Now create a new Category (not a sub-category) call ABC
Result: Red txt displays warning. To quick to read but appears it is saying ABC is a duplicate.
NOTE: I do not know what the implications of this may be or if there are other possible permutations. Logging this so we can discuss.

**Comment by rescobar2** [comment]
This may be related.
I’m building the Category and Sub-Category list. 
Every now and then I create a new Category and then a red txt msg flashes, I think it says duplicate. I check the list and it is not a duplicate. I delete it and remake without an issue.

**Comment by ecommarato** [comment]
Should be resolved now.

**Comment by rescobar2** [comment]
Verified as fixed in live environment. Closing 5-5-14
