### ISSUE TITLE
Require selection of External or Internal FAQ

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#29]
Create an FAQ but do not select flag Internal or External 
Result: The FAQ will not be found in a search result
Solution: Require section of External or Internal flag

**Comment by ecommarato** [comment]
Internal/External flag is now mandatory for new FAQs so this issue should be resolved going forward.

**Comment by rescobar2** [comment]
Verified as fixed 3-25-14 closing
