### ISSUE TITLE
Cannot open sent FAQ

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#3]
Login as Superuser
Search for an FAQ and send it as an email. 
"I sent it to ricke@toaelectronics.com"
When link arrives open it.
Result: 404 error
Expected: Should be able to open FAQ

**Comment by rescobar2** [comment]
Note that the content must be just the FAQ. We want to prevent the receiver of the email from navigating back to the FAQ site. This may change at some future date if TOA decides to make the site public.

**Comment by rescobar2** [comment]
Update: As of 3:20 PM 2-19-14 the FAQ link now works but sends you to a login page

**Comment by ecommarato** [comment]
The FAQ email now consists of the entire FAQ, no need to send them to a link

**Comment by rescobar2** [comment]
I can still duplicate this bug as of 5:08 PM 2-25-14 The link requires a login
![faq_email](https://f.cloud.github.com/assets/6641267/2265529/0893bae8-9e83-11e3-9e5b-5af2846cc91d.JPG)
14

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Lets discuss what is supported. For example if I try FAQ 33 Bears / Grizzly Bears the image of the bear is not sent.

**Comment by ecommarato** [comment]
Leaving open to resolve at time of launch because the domain will change for absolute links like images

**Comment by rescobar2** [comment]
verified as fixed on live environment. Closing 5-5-14
