### ISSUE TITLE
New Search window does not open

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#31]
Do a search that will turn up a result from:
http://www.toaelectronics.com/faq/

From Search Again, Select a Category and you this result;
![image](https://cloud.githubusercontent.com/assets/6641267/2884547/1ddd889c-d4ad-11e3-84bd-00ede8bb1670.png)

**Comment by rescobar2** [comment]
I tested this in IE 9

**Comment by ecommarato** [comment]
I am unable to reproduce.  Can you confirm the problem still occurs?

**Comment by ecommarato** [comment]
This bug is resolved.  Please let me know if you see it again on your end.

**Comment by rescobar2** [comment]
Not related to this project
