### ISSUE TITLE
TOA logo hyperlink leaves FAQ site

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#32]
open FAQ search page
http://www.toaelectronics.com/faq/

Click TOA logo
Result: User sent to www.toaelectronics.com
Expected: http://www.toaelectronics.com/faq/
NOTE: This may change but not until the FAQ site live in the company site.

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Verified as fixed 5-12-14, closing.
