### ISSUE TITLE
Export File does not include all projects which are listed on the web database

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#34]
If searched by the below conditions for example, I get 12 projects listed below. However if I click on “Export List” to obtain the exported excel file, it contains less (9) projects as you can see in the attached exported CSV file. Please see this bug 34 pdf of examples 

[bug 34.pdf](https://github.com/westoforange/TOA-Project-Registry/files/494245/bug.34.pdf)

**Comment by ecommarato** [comment]
The export link only exports materials from the projects. If a project has no items in the Bill of Materials, then it won't appear in the exported spreadsheet

**Comment by rescobar2** [comment]
Good enough, closing

**Comment by rescobar2** [comment]
close
