### ISSUE TITLE
using comma splits data into multi cells

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#35]
If a comma “,” is used in a text for input fields when adding new projects, that data is split into multi-different sections when the project data is exported as CSV file.

**Comment by rescobar2** [comment]
Changed P1

**Comment by ecommarato** [comment]
When exporting, all commas are now escaped out to prevent Excel from thinking they are part of a new row.  Ready for testing

**Comment by rescobar2** [comment]
Verified as fixed, 2-6-17 closing
