### ISSUE TITLE
Relocate the “Application” section to right below to “Type of Market”.

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#37]
Relocate the “Application” section to right below to “Type of Market”.

![relocate-application](https://cloud.githubusercontent.com/assets/6641267/18854717/46d5b9de-8402-11e6-9af2-20d6d04f4199.jpg)

**Comment by ecommarato** [comment]
Update in progress

**Comment by ecommarato** [comment]
Done!

**Comment by rescobar2** [comment]
Verified as fixed, closing
