### ISSUE TITLE
Add the following two items to “Dealer Type” pull-down menu

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#38]
![dealer-item](https://cloud.githubusercontent.com/assets/6641267/18854755/8c4b6784-8402-11e6-80db-0a7f0d833527.jpg)

**Comment by ecommarato** [comment]
In progress

**Comment by ecommarato** [comment]
Ready for review

**Comment by rescobar2** [comment]
Verified as fixed, closing
