### ISSUE TITLE
Updates for Export Function

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#40]
Please see this document which includes table formating
[TOA Project Registry Update Requests.docx](https://github.com/westoforange/TOA-Project-Registry/files/494271/TOA.Project.Registry.Update.Requests.docx)
#1: Add “Owned By” item.
#2: Add “Comment” item.
#3: Add “Dealer Type” item.
#4: Add “Application” Item
#5: Change the label for “Percent to Completion” to “%” (or “Progress” if “%” cannot be used for the label)
#6: Change the label for “Free Design” to “F/D” (or “FD” if “/” cannot be used for the label.)
#7: Change the label for “Area Number” to “Area #” (of “Area” if “#” cannot be used for the label.)
#8: Change the order of items generated. Please see below chart.

**Comment by rescobar2** [comment]
Here is a link to a jpg of the example 
![item list example](https://cloud.githubusercontent.com/assets/6641267/22036213/962a93b2-dca7-11e6-8f4c-ffcbc2f5a11a.jpg)

**Comment by ecommarato** [comment]
Done and ready for review!

**Comment by rescobar2** [comment]
Verified as fixed, closing
