### ISSUE TITLE
Cannot edit Owned By in a Project

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#41]
Edit a project
Issue: Cannot change who the project is
![edit-project](https://cloud.githubusercontent.com/assets/6641267/18967299/7a31f7e6-8639-11e6-998a-511ccfe15b6c.jpg)
 owned by

**Comment by rescobar2** [comment]
Erin this was a project created by  Speidel (kspeidel)

**Comment by ecommarato** [comment]
What permission level should be able to edit the owner of the project?

**Comment by rescobar2** [comment]
Group Manager should be able to make change

**Comment by ecommarato** [comment]
Will make this change for Manager and Superadmin permissions levels

**Comment by rescobar2** [comment]
Perfect thanks

**Comment by ecommarato** [comment]
This ticket is now ready for review

**Comment by rescobar2** [comment]
Verified as fixed, closing

**Comment by rescobar2** [comment]
close
