### ISSUE TITLE
Discount target gets flipped when project is viewed

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#42]
Open to
**New Project Details page and note Discounts**
Certification Discount (10% discount on all intercoms)
Registration Discount (10% discount on all products)
**Now view a created projected.**
**Project Information Page**
Certification Discount (10% all products): 
Registration Discount (10% on intercoms): 
**Result:** Discounts are flipped.
This is the correct Discount on the New Project Details Page.
Certification Discount (10% discount on all intercoms)
Registration Discount (10% discount on all products)
**Notice that the Discount is flipped from the Project Information page**
Certification Discount (10% all products): **"should be 10% all intercoms"**
Registration Discount (10% on intercoms): **"should be 10% all products"**

**Comment by ecommarato** [comment]
Fix in progress

**Comment by ecommarato** [comment]
Ready for review!

**Comment by rescobar2** [comment]
Verified as fixed 2-16-17, closed as fixed
