### ISSUE TITLE
Go Back button loses previous search result

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#43]
Search for Project DanS
Open Project 
Click Go Back button
Result: Original Search criteria lost
Expected: Original search is still available

**Comment by ecommarato** [comment]
Fix in progress

**Comment by ecommarato** [comment]
This has been resolved by opening the project in a new tab. User can close the tab when finished to return search page. Let me know if this works for you!

**Comment by rescobar2** [comment]
Works for me. Lets call it fixed
