### ISSUE TITLE
Need a way to set Search criteria to default

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#44]
From Home page search for a project
Result: There is not a way to reset the Search criteria back to default

**Comment by ecommarato** [comment]
In progress

**Comment by ecommarato** [comment]
Added a Clear button

**Comment by rescobar2** [comment]
Search button now restoring back to default.
1. Opening a new Search and clicking Clear button removes Any from Percent to Success (Min):
2. Change state of every field and click Clear Button
Result: Free Design remains checked, Product Number field not cleared, Percent to Success (Max): not reset, 	Percent to Success (Min): not restored to Any

**Comment by ecommarato** [comment]
All fixed. Note, the Model Number field is cleared on search because of its dynamic dropdown.  All others should remain when searching.

All fields are now being set to default when the Clear button is clicked.

**Comment by rescobar2** [comment]
Verified as fixed, closing
