### ISSUE TITLE
Percent to Success to "Any" as default

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#45]
Open to the Home > Search for Projects page
Notice that the default for "Percent to Success" drop downs use "0% Unstated"
Click Search:
Result: All records are found
Expected: Only records with 0% Unstated should have been found.
Note: Please set "Any" as default for "Percent to Success" search critera

**Comment by ecommarato** [comment]
In progress

**Comment by ecommarato** [comment]
Complete and ready for review

**Comment by rescobar2** [comment]
"Any" is not the default but if you click 	Clear Form button "Percent to Success (Min):" is rest to a empty selection.

A search for "0% Unstated" is finding projects other than 0%

**Comment by rescobar2** [comment]
This is example from Ueno
 
[percent to success - from Ueno.pdf](https://github.com/westoforange/TOA-Project-Registry/files/891256/percent.to.success.-.from.Ueno.pdf)

**Comment by ecommarato** [comment]
I see what's causing this, working on a fix

**Comment by ecommarato** [comment]
This issue is resolved, ready for review

**Comment by rescobar2** [comment]
I can still reproduce this bug. Can you give a ring?

**Comment by rescobar2** [comment]
Changed assignment to Erin

**Comment by ecommarato** [comment]
Yep, I can still reproduce it too. Got hung up on fixing the issue I saw in Ueno's screenshot

**Comment by ecommarato** [comment]
Ready for review!

**Comment by rescobar2** [comment]
Query Logic is still finding false positives.
Do a search for 	
Percent to Success (Min): = 0% Upstarted
Percent to Success (Max): = 0% Upstarted
Result: 5 pages of results
Expected: Should only find 0% Upstarted

**Comment by ecommarato** [comment]
Fixed for good! (I hope!)

**Comment by rescobar2** [comment]
Verified as fixed, closing
