### ISSUE TITLE
Price Range search criteria not implemented  

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#46]
Go to Home > Search for Projects
For price enter value range $25,000 to $9,000
Do Search
Result: All projects found have a zero value.
Note: If I do not use the dollar sign $ nothing is found. Looks like Price Range search criteria not implemented .

**Comment by ecommarato** [comment]
The price range fields search from low to high, will add something to filter out '$' symbol and placeholder text to indicate order (low to high)

**Comment by ecommarato** [comment]
Done, ready for review!

**Comment by rescobar2** [comment]
Verified as fixed 2-16-17, closing
