### ISSUE TITLE
Anticipated Close Date not recording to save project

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#47]
Open to Project Manager > Add New Project
Create a new project
In this project enter a "Anticipated Close Date"
Save the project
Now search and open the project
Result: "Anticipated Close Date" = N/A

**Comment by ecommarato** [comment]
Fix in progress

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Verified as fixed 2-16-17, closing
