### ISSUE TITLE
Need Permission spec for groups

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#48]
Erin can you send me what the permissions are for the all the Groups. I just discovered that group "Customer Service" can create a new project but not edit. My understand is that "Customer Service" should be a view only permission.

**Comment by rescobar2** [comment]
I also will want to delete the test user groups unless they are still neeeded

**Comment by ecommarato** [comment]
Research in progress

**Comment by ecommarato** [comment]
I have highlighted areas that appear to be misconfigured. Please review and let me know your thoughts on all permissions.

[Permissions Graph.xlsx](https://github.com/westoforange/TOA-Project-Registry/files/775070/Permissions.Graph.xlsx)

**Comment by rescobar2** [comment]
Ask Kevin W to review permission levels

**Comment by rescobar2** [comment]
I'm closing and leaving as is for now
