### ISSUE TITLE
Cannot delete a an item from Project Information

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#49]
Add some products "Bill of Materials" to a Project
Attempt to remove a product
Result: There is not a way to delete a line item, I can reduce to zero but not delete a row. If QTY is = to zero you should be able to delete the row. See image.
![bill-of-materials](https://cloud.githubusercontent.com/assets/6641267/19135976/a3b941f8-8b1d-11e6-943b-898ddfee20cd.jpg)

**Comment by ecommarato** [comment]
Line items are now able to be deleted, regardless of QTY

**Comment by rescobar2** [comment]
Verified as fixed, closing
