### ISSUE TITLE
Login field missing from password recovery page

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#5]
From Frontend Staging URL: http://toa.webdevstaging.com/faq
Click Forgot Password
From received open link and reset password
Result: Password is reset but there is not a login field 
See attached image
![pw-reset](https://f.cloud.github.com/assets/6641267/2140617/a4d8ebac-934e-11e3-84fb-da0635451b13.jpg)

**Comment by ecommarato** [comment]
Login box added to this page

**Comment by rescobar2** [comment]
verified as fixed 2-19-14
