### ISSUE TITLE
Duplicate Project ID can be entered

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#50]
Create a new Project
Use ID: "enter a value"
Save the Project
Create another Project and use the same ID from the previous saved project.
Result: Duplicate ID's are allowed to be used.

**Comment by ecommarato** [comment]
Fix in progress

**Comment by ecommarato** [comment]
Ready for review!

**Comment by rescobar2** [comment]
Cannot enter duplicate project number, verified as fixed, closing 2-16.17
