### ISSUE TITLE
A blank Category can be created

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#52]
Open to Modules > Products > Products Manager
Click Add New Category
Click Save without entering any information
Result: A empty Category is created
Expected: Should require all fields to be completed before a Save is processed

**Comment by rescobar2** [comment]
Only Category Name should be required

**Comment by rescobar2** [comment]
changed to P3

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Verified as fixed, closing
