### ISSUE TITLE
New category not added in alphanumeric order

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#53]
Open to Modules > Products > Products Manager
Click "Add New Category" button
Create a new category such as "Test"
Result: New Category is not added alphanumeric order.
Note: I could live with this but there is not a way to to resort as a work around.

**Comment by rescobar2** [comment]
I see now that you can manually drag Categories by the X. Is adding a sort feature possible?

**Comment by ecommarato** [comment]
This can be changed to either manually sortable or automatically sortable in alphabetical order. Which would be preferred?

**Comment by rescobar2** [comment]
Let's go with auto sort

**Comment by rescobar2** [comment]
Please use auto sort

**Comment by ecommarato** [comment]
Categories are now sorted alphanumerically. However, products are still sorted in drag and drop order. Do you want us to change products too?

**Comment by rescobar2** [comment]
Verified as fixed, closing
