### ISSUE TITLE
URL already in use 

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#55]
Open to Products Manager > Category > "Category being tested"
Click "Add New Product" button
Save Product without adding a URL
Result: Error msg that URL is already in use
![url in use](https://cloud.githubusercontent.com/assets/6641267/19207796/a71403ce-8ca8-11e6-9c1b-db8ed41a84da.jpg)

**Comment by ecommarato** [comment]
Fix in progress

**Comment by ecommarato** [comment]
Ready for review!

**Comment by rescobar2** [comment]
Verified as fixed, closing 2-16-17
