### ISSUE TITLE
Entered Products with prices not appearing in the Project Edit window

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#56]
Search for project JF1204-test
Edit Project
Result: There will not be any products listed with prices.
Expected: User entered N-8000RS, N-8600MS, N-8000DI with products with prices should be listed.
NOTE: If you export the Project to Excel the following products with prices will be found.
N-8000RS, N-8600MS, N-8000DI

**Comment by ecommarato** [comment]
This happens when looking at a specific location, for which there are no products. (Dallas, TX). If you switch to Default location, you see those products that you are referencing.

Only products that were added for that specific location will show.

**Comment by rescobar2** [comment]
Closing not a bug
