### ISSUE TITLE
Add Search by Dealer

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#57]
<Updates for Project Search Features>
#1: Add “Dealer” for the project search item.
#2: Change the name of project search item for product category from current “Category” to “Product Category”.
#3: Create two difference items for “Date Range” search; One for “Created On” and another for “Last Updated”.
#4: Change the project search layout (in different order as shown below)
![search-projects](https://cloud.githubusercontent.com/assets/6641267/22035452/ec3e4eae-dca4-11e6-8250-32576a4832d4.jpg)

**Comment by rescobar2** [comment]
https://cloud.githubusercontent.com/assets/6641267/22035452/ec3e4eae-dca4-11e6-8250-32576a4832d4.jpg

**Comment by rescobar2** [comment]
![image](https://cloud.githubusercontent.com/assets/6641267/22035591/596a875e-dca5-11e6-9a9d-317330dc8738.png)

**Comment by ecommarato** [comment]
Ready for review/testing

**Comment by rescobar2** [comment]
Order of items does not match sample image. Product Category should be after Region but it is currently not. Rest of of fix looks correct.

**Comment by rescobar2** [comment]
Changed Ownership

**Comment by ecommarato** [comment]
Adjusted order per sample image

**Comment by rescobar2** [comment]
Verified as fixed 2-6-17
