### ISSUE TITLE
Add items MNS/Emergency and to Others Project Info

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#58]
<Updates for Project Info Input Feature>
Add the following two items MNS/Emergency and to Others to “Application” pull-down menu.
-	BGM
-	Conferencing
-	Intercom
-	Live Reinforcement
-	Paging
-	Public Address
-	Room-Combining
-	MNS/Emergency
-	Others

**Comment by ecommarato** [comment]
Update in progress

**Comment by ecommarato** [comment]
Done!

**Comment by rescobar2** [comment]
Verified as fixed 2-16-17, closing
