### ISSUE TITLE
Ability to use current pricing

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#59]
Erin,

Can you please discuss this topic with Kevin Wilkin? He would like the ability to use pricing from their pricing spreadsheet. 

Currently the the Pricing on the online registry is coming up with 2016 pricing – standard level only. Rick

**Comment by ecommarato** [comment]
Got it! I'll bring this up with Kevin

**Comment by ecommarato** [comment]
Currently working on this upgrade with Kevin
