### ISSUE TITLE
Duplicate emails blocks password recovery

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#6]
Steps:
1. From the Admin page create a new Group User with a valid email address
2. From Frontend Staging URL: http://toa.webdevstaging.com/faq
3. Click Forgot Password, enter email address from Step 1 and submit
Result 1: The password recovery email is sent.
4. Create a new Group SuperUser with the same password as used in Step 1.
5. Click Forgot Password, enter email address and submit.
Result: Password not found

**Comment by ecommarato** [comment]
emails must now be unique across all accounts

**Comment by rescobar2** [comment]
As of 5 PM 2-25-14 I was able to create a new user with previously used email address. 
Also currently I cannot request a new password IF:
- two or more accounts with duplicate email address that has only one active

**Comment by ecommarato** [comment]
Resolved with fix to Add Account - The Add Account form will no longer allow accounts to be added with duplicate emails

**Comment by rescobar2** [comment]
Verified fixed 3-18-14 closing
