### ISSUE TITLE
In Project Search default Percent to Success is set to 0%

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#61]
Open to Search for Projects
In Project Search, the default Percent to Success is set to 0%
Expected: Percent to Success should be Any as the default

**Comment by erin-commarato** [comment]
Resolved, ready for review!

**Comment by ecommarato** [comment]
Resolved, ready for review!

**Comment by rescobar2** [comment]
Verified as fixed, closing
