### ISSUE TITLE
Owner will change to Editor

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#63]
Search for an existing test Project ( I used ID king1), Owned by = Rick-PR-Test
Edit the Project Details
Result: Owned by will change to "Editor"
Expected: Owned by = should not change to "Editor". In my example it should have remained as Rick-PR-Test

**Comment by ecommarato** [comment]
Resolved, ready for review!

**Comment by rescobar2** [comment]
Verified as fixed, closed
