### ISSUE TITLE
Deleting a project results in refreshed search result

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#65]
Search for a collection of projects that finds 4 results
Delete one project
Result: Listed projects refreshes and lists all projects
Expected: The prior result should show 3 results
NOTE: I accidentally deleted a project, my fault but did not realize the list was refreshed. Safer this way.

**Comment by ecommarato** [comment]
Ready for review!

**Comment by rescobar2** [comment]
Verified as fixed, closing
