### ISSUE TITLE
Duplicate Categories can be created

### ISSUE THREAD

**Issue by rescobar2** [westoforange/TOA-Project-Registry#9]
Steps:

Create a new Category
Create a new Category using the same name
Result: Duplicate Categories created
NOTE: Duplicate Subcategories cannot be created which is expected behavior.

**Comment by ecommarato** [comment]
Resolved

**Comment by rescobar2** [comment]
Reopening 3-19-14. This bug has come back.

**Comment by ecommarato** [comment]
Resolved again!

**Comment by rescobar2** [comment]
Verified as fixed 3-31-14 closed
